# Spring
spring:

  # JDBC configuration
  datasource:
    url: jdbc:h2:mem:cameradb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update

  # H2 configuration
  h2:
    console:
      enabled: true
      path: /h2

  servlet:
    multipart:
      enabled: true
      max-request-size: 25MB
      max-file-size: 20MB

# Logging
logging.file: camera-service.log
logging:
  file:
    max-size: 1MB
    max-history: 10
  level:
    root: WARN
    org:
      springframework: INFO
    me:
      wirries:
        smartcamera:
          cameraservice: DEBUG

# Application
app:
  security:
    enable: false
    username: user
    password: xxx